;;; pinboard-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from pinboard.el

(autoload 'pinboard-add "pinboard" "\
Add a new pin to Pinboard." t)
(autoload 'pinboard-visit-pinboard "pinboard" "\
Visit pinboard.in itself." t)
(autoload 'pinboard-add-for-later "pinboard" "\
Quickly add URL for later review and reading.

This command simply prompts for a URL and adds it to Pinboard as
private and unread, so you can come back to it and look at it
later.

(fn URL)" t)
(autoload 'pinboard "pinboard" "\
Browse your Pinboard pins.

Key bindings that are active in the pin list include:

\\{pinboard-mode-map}" t)
(register-definition-prefixes "pinboard" '("pinboard-"))

;;; End of scraped data

(provide 'pinboard-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; pinboard-autoloads.el ends here
