;;; espotify-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from espotify.el

(autoload 'espotify-format-item "espotify" "\
Format the search result ITEM as a string with additional metadata.
The metadata will be accessible via `espotify-candidate-metadata'.

(fn ITEM)")
(autoload 'espotify-candidate-metadata "espotify" "\
Extract from CAND (as returned by `espotify-format-item') its metadata.

(fn CAND)")
(autoload 'espotify-play-uri "espotify" "\
Use a DBUS call to play a URI denoting a resource.

(fn URI)")
(autoload 'espotify-play-candidate "espotify" "\
If CAND is a formatted item string and it has a URL, play it.

(fn CAND)")
(autoload 'espotify-play-pause "espotify" "\
Toggle default Spotify player via DBUS." t)
(autoload 'espotify-next "espotify" "\
Tell default Spotify player to play next track via DBUS." t)
(autoload 'espotify-previous "espotify" "\
Tell default Spotify player to play previous track via DBUS." t)
(autoload 'espotify-show-candidate-info "espotify" "\
Show low-level info (an alist) about CANDIDATE.

(fn CANDIDATE)")
(autoload 'espotify-play-candidate-album "espotify" "\
Play album associated with selected CANDIDATE.

(fn CANDIDATE)")
(autoload 'espotify-candidate-url "espotify" "\
Retrieve the spotify URL for the given CANDIDATE.

(fn CANDIDATE)")
(register-definition-prefixes "espotify" '("espotify-"))

;;; End of scraped data

(provide 'espotify-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; espotify-autoloads.el ends here
