;;; compile-multi-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from compile-multi.el

(autoload 'compile-multi "compile-multi" "\
Multi-target interface to compile.
With optional argument QUERY allow user to modify compilation command before
running.

(fn &optional QUERY)" t)
(register-definition-prefixes "compile-multi" '("compile-multi-"))

;;; End of scraped data

(provide 'compile-multi-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; compile-multi-autoloads.el ends here
