;;; helm-recoll-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from helm-recoll.el

(autoload 'helm-recoll-create-source "helm-recoll" "\
Create helm source and associated functions for recoll search results.
The first argument NAME is a string.  Define a source variable
named `helm-source-recoll-NAME' and a command named
`helm-recoll-NAME'.  CONFDIR is the path to the config directory
which recoll should use.

(fn NAME CONFDIR)")
(autoload 'helm-recoll "helm-recoll" "\
Select recoll sources for helm." t)
(register-definition-prefixes "helm-recoll" '("helm-recoll-"))

;;; End of scraped data

(provide 'helm-recoll-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; helm-recoll-autoloads.el ends here
