;;; calibredb-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from calibredb.el

(autoload 'calibredb "calibredb" "\
Enter calibre Search Buffer." t)


;;; Generated autoloads from calibredb-annotation.el

(register-definition-prefixes "calibredb-annotation" '("calibredb-"))


;;; Generated autoloads from calibredb-consult.el

(autoload 'calibredb-consult-ripgrep-all "calibredb-consult" "\
Search with `rga` for files in DIR where the content matches a regexp.
  The initial input is given by the INITIAL argument. See `consult-grep`
  for more details.

(fn &optional DIR INITIAL)" t)
(register-definition-prefixes "calibredb-consult" '("calibredb-consult-"))


;;; Generated autoloads from calibredb-core.el

(register-definition-prefixes "calibredb-core" '("calibredb-"))


;;; Generated autoloads from calibredb-dired.el

(register-definition-prefixes "calibredb-dired" '("calibredb-dired-"))


;;; Generated autoloads from calibredb-helm.el

(register-definition-prefixes "calibredb-helm" '("calibredb-"))


;;; Generated autoloads from calibredb-ivy.el

(autoload 'calibredb-find-counsel "calibredb-ivy" "\
Use counsel to list all ebooks details." t)
(register-definition-prefixes "calibredb-ivy" '("calibredb-"))


;;; Generated autoloads from calibredb-library.el

(autoload 'calibredb-switch-library "calibredb-library" "\
Swich Calibre Library." t)
(autoload 'calibredb-library-list "calibredb-library" "\
Switch library from variable `calibredb-library-alist'.
If under *calibredb-search* buffer, it will auto refresh after
selecting the new item." t)
(register-definition-prefixes "calibredb-library" '("calibredb-"))


;;; Generated autoloads from calibredb-opds.el

(register-definition-prefixes "calibredb-opds" '("calibredb-opds-"))


;;; Generated autoloads from calibredb-org.el

(autoload 'calibredb-org-link-view "calibredb-org" "\
Follow calibredb org links by ID.

(fn ID _)")
(autoload 'calibredb-org-complete-link "calibredb-org" "\
Define completion for Org \"calibredb:\" links.
The optional PREFIX argument is ignored.
Please notice: `calibredb-id-width' must >= the real id lenth.

(fn &optional PREFIX)")
(register-definition-prefixes "calibredb-org" '("calibredb-org-"))


;;; Generated autoloads from calibredb-search.el

(register-definition-prefixes "calibredb-search" '("calibredb-"))


;;; Generated autoloads from calibredb-show.el

(register-definition-prefixes "calibredb-show" '("calibredb-"))


;;; Generated autoloads from calibredb-transient.el

(register-definition-prefixes "calibredb-transient" '("calibredb-"))


;;; Generated autoloads from calibredb-utils.el

(autoload 'calibredb-list "calibredb-utils" "\
Generate an org buffer which contain all ebooks' cover image, title and the file link." t)
(register-definition-prefixes "calibredb-utils" '("calibredb-"))

;;; End of scraped data

(provide 'calibredb-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; calibredb-autoloads.el ends here
