;;; sdcv-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from sdcv.el

(autoload 'sdcv-mode "sdcv" "\
Major mode to look up word through sdcv.
\\{sdcv-mode-map}
Turning on Text mode runs the normal hook `sdcv-mode-hook'.

(fn)" t)
(autoload 'sdcv-search-pointer "sdcv" "\
Get current word.
And display complete translations in other buffer.

(fn &optional WORD)" t)
(autoload 'sdcv-search-pointer+ "sdcv" "\
Translate current point word.
And show information use tooltip.
But this function use a simple dictionary list." t)
(autoload 'sdcv-search-input "sdcv" "\
Translate current input WORD.
And show information in other buffer.

(fn &optional WORD)" t)
(autoload 'sdcv-search-input+ "sdcv" "\
Translate current point WORD.
And show information use tooltip.

(fn &optional WORD)" t)
(register-definition-prefixes "sdcv" '("sdcv-"))

;;; End of scraped data

(provide 'sdcv-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; sdcv-autoloads.el ends here
