;;; basic-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from basic-mode.el

(autoload 'basic-mode "basic-mode" "\
Major mode for editing BASIC code.

The base mode provides basic functionality and is normally
only used to derive sub modes for different BASIC dialects,
see for example `basic-generic-mode'.

Commands:

\\[indent-for-tab-command] indents for BASIC code.

\\[newline] can automatically insert a fresh line number if
`basic-auto-number' is set.  Default is disabled.

\\[xref-find-definitions] looks up the identifier at point.

Customization:

You can customize the indentation of code blocks, see variable
`basic-indent-offset'.  The default value is 4.

Formatting is also affected by the customizable variables
`basic-delete-trailing-whitespace' and `delete-trailing-lines'
(from simple.el).

You can also customize the number of columns to allocate for line
numbers using the variable `basic-line-number-cols'. The default
value of 0, no space reserved, is appropriate for programs with
no line numbers and for left aligned numbering. Use a larger
value if you prefer right aligned numbers. Note that the value
includes the space after the line number, so 6 right aligns
5-digit numbers.

The other line number features can be configured by customizing
the variables `basic-auto-number', `basic-renumber-increment' and
`basic-renumber-unnumbered-lines'.

Whether syntax highlighting requires separators between keywords
can be customized with variable
`basic-syntax-highlighting-require-separator'.

\\{basic-mode-map}

(fn)" t)
(autoload 'basic-dartmouth-mode "basic-mode" "\
Programming mode for Dartmouth BASIC, editions one to four.
Derived from `basic-mode'.

(fn)" t)
(autoload 'basic-trs80-mode "basic-mode" "\
Programming mode for BASIC on the TRS-80 Model I and III.
For the TRS-80 Model 100 BASIC and TRS-80 Color Computer BASIC,
please see `basic-m100-mode` and `basic-coco-mode`.
Derived from `basic-mode'.

(fn)" t)
(autoload 'basic-m100-mode "basic-mode" "\
Programming mode for BASIC for the TRS-80 Model 100 computer.
Also works for the other Radio-Shack portable computers (the
Tandy 200 and Tandy 102), the Kyocera Kyotronic-85, and the
Olivetti M10. Additionally, although N82 BASIC is slightly
different, the NEC family of portables (PC-8201, PC-8201A, and
PC-8300) are also supported by this mode.

(fn)" t)
(autoload 'basic-zx81-mode "basic-mode" "\
Programming mode for BASIC for ZX81 machines.
Derived from `basic-mode'.

(fn)" t)
(autoload 'basic-spectrum-mode "basic-mode" "\
Programming mode for BASIC for ZX Spectrum machines.
Derived from `basic-zx81-mode'.

(fn)" t)
(autoload 'basic-qb45-mode "basic-mode" "\
Programming mode for Microsoft QuickBasic 4.5.
Derived from `basic-mode'.

(fn)" t)
(autoload 'basic-generic-mode "basic-mode" "\
Generic BASIC programming mode.
This is the default mode that will be used if no sub mode is specified.
Derived from `basic-qb45-mode'.  For more information, see `basic-mode'.

(fn)" t)
 (add-to-list 'auto-mode-alist '("\\.bas\\'" . basic-generic-mode))
(register-definition-prefixes "basic-mode" '("basic-"))

;;; End of scraped data

(provide 'basic-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; basic-mode-autoloads.el ends here
