;;; consult-projectile-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from consult-projectile.el

(autoload 'consult-projectile-switch-to-buffer "consult-projectile" "\
Swith to a project buffer using `consult'." t)
(autoload 'consult-projectile-switch-to-buffer-other-window "consult-projectile" "\
Swith to a project buffer using `consult'." t)
(autoload 'consult-projectile-switch-to-buffer-other-frame "consult-projectile" "\
Swith to a project buffer using `consult'." t)
(autoload 'consult-projectile-find-dir "consult-projectile" "\
Jump to a project's directory using `consult'." t)
(autoload 'consult-projectile-find-file "consult-projectile" "\
Jump to a project's file using `consult'." t)
(autoload 'consult-projectile-find-file-other-window "consult-projectile" "\
Jump to a project's file using `consult'." t)
(autoload 'consult-projectile-find-file-other-frame "consult-projectile" "\
Jump to a project's file using `consult'." t)
(autoload 'consult-projectile-recentf "consult-projectile" "\
Show a list of recently visited files in a project using `consult'." t)
(autoload 'consult-projectile-switch-project "consult-projectile" "\
Switch to a projectile visted before using `consult'." t)
(autoload 'consult-projectile "consult-projectile" "\
Create a multi view with projectile integration.   Displays known projects when there are none or the buffers/files accociated with the project.

(fn &optional SOURCES)" t)
(register-definition-prefixes "consult-projectile" '("consult-projectile-"))

;;; End of scraped data

(provide 'consult-projectile-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; consult-projectile-autoloads.el ends here
