;;; consult-project-extra-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from consult-project-extra.el

(autoload 'consult-project-extra-find "consult-project-extra" "\
Create an endpoint for accessing different project sources.
The consult view can be narrowed to: (b) current project's buffers,(f) current
project's files and (p) to select from the list of known projects.

The buffer and project file sources are only enabled in case that the user is
in a project file/buffer.  See `project-current'.

A different action is issued depending on the source.  For both buffers and
project files, the default action is to visit the selected element.  When a
known project is selected, a list to select from is created with the selected
project's files" t)
(autoload 'consult-project-extra-find-other-window "consult-project-extra" "\
Variant of `consult-project-extra' which opens in a second window." t)
(register-definition-prefixes "consult-project-extra" '("consult-project-extra-"))

;;; End of scraped data

(provide 'consult-project-extra-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; consult-project-extra-autoloads.el ends here
