;;; consult-spotify-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from consult-spotify.el

(autoload 'consult-spotify-album "consult-spotify" "\
Query spotify for an album using consult." t)
(autoload 'consult-spotify-artist "consult-spotify" "\
Query spotify for an artist using consult." t)
(autoload 'consult-spotify-track "consult-spotify" "\
Query spotify for a track using consult." t)
(autoload 'consult-spotify-playlist "consult-spotify" "\
Query spotify for a track using consult." t)
(register-definition-prefixes "consult-spotify" '("consult-spotify-"))

;;; End of scraped data

(provide 'consult-spotify-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; consult-spotify-autoloads.el ends here
