;;; consult-recoll-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from consult-recoll.el

(autoload 'consult-recoll "consult-recoll" "\
Consult recoll's local index.
With prefix argument ASK, the user is prompted for an initial query string.

(fn ASK)" t)
(autoload 'consult-recoll-embark-setup "consult-recoll" "\
Set up integration with embark.
In particular, allow opening candidates from embark-collect
buffers.")
(register-definition-prefixes "consult-recoll" '("consult-recoll-"))

;;; End of scraped data

(provide 'consult-recoll-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; consult-recoll-autoloads.el ends here
